spring:
  thymeleaf:
    cache: false
    prefix: /WEB-INF/views/
    suffix: .jsp
    enabled: false
  datasource:
    url: jdbc:mysql://113.198.164.155:3306/jeju?characterEncoding=utf-8
    username: jeju
    password: jejupw
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: /WEB-INF/views/spring/resources
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
