spring:
  thymeleaf:
    cache: false
    suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost/jeju?characterEncoding=utf-8
    username: jeju
    password: jejupw
    driver-class-name: com.mysql.jdbc.Driver

